# Generated by Django 4.1 on 2022-11-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=100)),
                ('custemail', models.CharField(max_length=100)),
                ('custpass', models.CharField(max_length=15)),
                ('custno', models.CharField(max_length=15)),
                ('custaddress', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuImage', models.URLField(null=True)),
                ('menuid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('menuname', models.CharField(max_length=255)),
                ('menuprice', models.CharField(max_length=10)),
                ('menudesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.menu')),
            ],
        ),
    ]
