# Generated by Django 4.1 on 2022-11-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('menuid', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
