# Generated by Django 4.1 on 2022-11-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
